/*
    {
        title: "",
        img: ,
        rating: ,
        rating_num: ,
        strength: ,
        hypertrophy: ,
        endurance: ,
        type: ,
    },
*/
import benchpress from "../images/benchpress.jpeg";
import deadlift from "../images/deadlift.jpeg";
import squat from "../images/squat.jpeg";
import military_press from "../images/Military_press.jpeg";
import bent_over_row from "../images/bent_over_row.jpeg";
import chin_up from "../images/chin_up.jpeg";
import dumbell_curl from "../images/dumbell_curl.jpeg";
import lateral_raise from "../images/lateral_raise.jpeg";
import tricep_extension from "../images/tricep_extension.jpeg";
import running from "../images/running.jpeg";
import swimming from "../images/swimming.jpeg";
import jump_rope from "../images/jump_rope.jpeg";

export const exercises = [
    {
        title: "Bench Press",
        title_fr: "Développé couché",
        img: benchpress,
        rating: 5,
        rating_num: 5.6,
        strength: true,
        hypertrophy: true,
        endurance: false,
        type: "push",
        link: "https://www.youtube.com/watch?v=gRVjAtPip0Y",
    },
    {
        title: "Squat",
        title_fr: "Squat",
        img: squat,
        rating: 5,
        rating_num: 4.3,
        strength: true,
        hypertrophy: true,
        endurance: false,
        type: "legs",
        link: "https://www.youtube.com/watch?v=gcNh17Ckjgg",
    },
    {
        title: "Dumbell curl",
        title_fr: "Flexion des haltères",
        img: dumbell_curl,
        rating: 5,
        rating_num: 6.2,
        strength: false,
        hypertrophy: true,
        endurance: false,
        type: "pull",
        link: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
    },
    {
        title: "Jump-rope",
        title_fr: "Corde à sauter",
        img: jump_rope,
        rating: 4,
        rating_num: 1.1,
        strength: false,
        hypertrophy: false,
        endurance: true,
        type: "endurance",
        link: "https://www.youtube.com/watch?v=FJmRQ5iTXKE",
    },
    {
        title: "Chin-ups",
        title_fr: "Pompes à main",
        img: chin_up,
        rating: 4,
        rating_num: 6.9,
        strength: false,
        hypertrophy: true,
        endurance: false,
        type: "pull",
        link: "https://www.youtube.com/watch?v=brhRXlOhsAM",
    },
    {
        title: "Swimming",
        title_fr: "Natation",
        img: swimming,
        rating: 4,
        rating_num: 1.3,
        strength: false,
        hypertrophy: false,
        endurance: true,
        type: "endurance",
        link: "https://www.youtube.com/watch?v=oM4sHl1hTEE",
    },
    {
        title: "Lateral Raises",
        title_fr: "Elévations latérales",
        img: lateral_raise,
        rating: 4,
        rating_num: 4.1,
        strength: false,
        hypertrophy: true,
        endurance: false,
        type: "push",
        link: "https://www.youtube.com/watch?v=b_LEX4n9lOs",
    },
    {
        title: "Bent over rows",
        title_fr: "Rameaux pliés",
        img: bent_over_row,
        rating: 4,
        rating_num: 3.1,
        strength: true,
        hypertrophy: true,
        endurance: false,
        type: "pull",
        link: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ",
    },
    {
        title: "Tricep extension",
        title_fr: "Extension du triceps",
        img: tricep_extension,
        rating: 3,
        rating_num: 2.7,
        strength: true,
        hypertrophy: true,
        endurance: false,
        type: "push",
        link: "https://www.youtube.com/watch?v=_gsUck-7M74",
    },
    {
        title: "Military Press",
        title_fr: "Presse militaire",
        img: military_press,
        rating: 3,
        rating_num: 1.8,
        strength: true,
        hypertrophy: true,
        endurance: false,
        type: "push",
        link: "https://www.youtube.com/watch?v=KP1sYz2VICk",
    },
    {
        title: "Deadlift",
        title_fr: "Levée de terre",
        img: deadlift,
        rating: 3,
        rating_num: 3.6,
        strength: true,
        hypertrophy: false,
        endurance: false,
        type: "legs",
        link: "https://www.youtube.com/watch?v=r4MzxtBKyNE",
    },
    {
        title: "Running",
        title_fr: "La course à pied",
        img: running,
        rating: 3,
        rating_num: 3.8,
        strength: false,
        hypertrophy: false,
        endurance: true,
        type: "endurance",
        link: "https://www.youtube.com/watch?v=28KR2wmGGh0",
    },
]